version: "3.9"
services:
  mysql:
    container_name: jc_storage_db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT:-3307}:3306"
    volumes:
      - jc_storage_data:/var/lib/mysql

volumes:
  jc_storage_data:
    driver: local
